### ISSUE TITLE
Integration With Android

### ISSUE THREAD

**Issue by iamvikashh** [breakfastquay/rubberband#104]
I am trying to create a pitch shifting app using rubber band and i need some help.
I can't find any proper documentation for the same. I have tried some 3 rd party Github projects that uses Rubber band but those repos are not  working.

Please help me out if its possible. If you got any doc or something that i can refer.

Thanks

**Comment by cannam** [comment]
Hi there - We haven't any meaningful Android capability here I'm afraid; I only know a handful of examples (the ones linked at the bottom of [this doc page](https://breakfastquay.com/rubberband/integration.html#examples)) and I have little insight into how well they work.

If any other readers can point to other examples or comment on their own experience, that would be very helpful!

**Comment by iamvikashh** [comment]
I Tried things on my own. i am able to successfully build the .so files which is required for integration in android.
Will try to use it with my project. till then if someone looking for latest android.mk file
 `LOCAL_PATH := $(call my-dir)
RUBBERBAND_SRC_PATH := $(LOCAL_PATH)/..

include $(CLEAR_VARS)

LOCAL_MODULE := rubberband

# Using the single-file build option
LOCAL_SRC_FILES := $(RUBBERBAND_SRC_PATH)/single/RubberBandSingle.cpp

# Specify the include directories
LOCAL_C_INCLUDES := \
    $(RUBBERBAND_SRC_PATH)/single

# Set the C++ standard to C++11 or later
LOCAL_CPPFLAGS := -std=c++11

# Enable exceptions
LOCAL_CPPFLAGS += -fexceptions

# Link against the C++ shared library (you may also use libc++_static for a static link)
LOCAL_LDLIBS := -lc++_shared

include $(BUILD_SHARED_LIBRARY)
`

**Comment by iamvikashh** [comment]
closing it as I was able to succesfully integrate it with android.
Reference: [https://github.com/iamvikashh/rubberbandAndroidImplementation](url)
