### ISSUE TITLE
Problem with Makefile.osx with FFTW3 and LIBSAMPLERATE

### ISSUE THREAD

**Issue by tangkk** [breakfastquay/rubberband#12]
on Mac (mine is 10.13), if we simply set -DHAVE_LIBSAMPLERATE -DHAVE_FFTW3 flag and change LIBRARY_LIBS accordingly (-L/usr/local/lib -lsamplerate -L/usr/local/lib -lfftw3), the make just doesn't work. There're still a lot of undefined symbols. In order to make it work, we need to set:
-DHAVE_LIBSAMPLERATE -DHAVE_FFTW3 -DFFTW_DOUBLE_ONLY
Please also fix this in the README, thanks:)

Actually I think what most people would like to see is a universal "configuire and make" system for both linux and mac, or you could make it a cmake supportable. Just to get rid of the Makefile.osx

**Comment by cannam** [comment]
Add `-lfftw3f` in the link line, as well as `-lfftw3`.

The FFTW libraries are split into single- and double-precision variants, and both are required. The FFTW_SINGLE_ONLY and FFTW_DOUBLE_ONLY options are provided in case you can't or don't want to link both, but in a typical build it's better to omit them.

**Comment by cannam** [comment]
Build system replaced by Meson, rendering obsolete this query.
