### ISSUE TITLE
Add to conda

### ISSUE THREAD

**Issue by beasteers** [breakfastquay/rubberband#16]
This should be installable via `conda install` :)

**Comment by cannam** [comment]
I'm not sure this was ever really an actionable request for me - I've never used conda in earnest, have no idea how to make something be installable with it, and I understood it to be primarily a Python environment whereas this project contains no Python. As this has been open a while without inspiring more than confusion on my part, I'm afraid I'm going to close it as not something I plan to resolve - sorry about that.
