### ISSUE TITLE
make install fails when jni isn't built

### ISSUE THREAD

**Issue by TexasDex** [breakfastquay/rubberband#17]
In the makefile, the 'all' target doesn't build JNI.  Which is good--I don't want to build JNI, I'm just using this for ffmpeg.  But then the 'install' target tries to copy the librubberband-jni.so file, and fails, and as a result, the pc file isn't created and the install is useless:
    cp -f lib/librubberband-jni.so /home/texasdex/target/lib/librubberband-jni.so
    cp: cannot stat ‘lib/librubberband-jni.so’: No such file or directory

I'm not a makefile expert but I checked with someone who was and they said I wasn't doing anything wrong, the issue was with the makefile itself.

I can work around this with make install JNI_TARGET=/dev/null but that's an awful hack that results in an empty file being installed--not ideal.

**Comment by davidhealey** [comment]
I had the same problem, thanks for letting me know about the workaround.

**Comment by vacing** [comment]
same problem, I comment the line copying librubberband-jni.so in target install then it all went well(inlcuding compile FFmpeg)
but I think there should have a better solution

**Comment by cannam** [comment]
Thanks for the report and apologies for the delay - have pushed a fix now. The target is installed only if the file exists in the build tree.

**Comment by magnetophon** [comment]
@cannam Thanks for the fix!
Have you considered doing a bugfix release?
