### ISSUE TITLE
Mismatch between C++ and C option values

### ISSUE THREAD

**Issue by mjbshaw** [breakfastquay/rubberband#19]
[In C++:](https://github.com/breakfastquay/rubberband/blob/0f8072c47e2c778e4e752bb4cd785890f05287ed/rubberband/RubberBandStretcher.h#L308-L309)

```C++
OptionPitchHighSpeed   = 0x00000000,
OptionPitchHighQuality = 0x02000000,
```

[In C:](https://github.com/breakfastquay/rubberband/blob/0f8072c47e2c778e4e752bb4cd785890f05287ed/rubberband/rubberband-c.h#L81-L82)
```C
RubberBandOptionPitchHighQuality = 0x00000000,
RubberBandOptionPitchHighSpeed   = 0x02000000,
```

The enum order (and values) are swapped in the C and C++ headers.

**Comment by cannam** [comment]
Ouch! Thanks for the report. The C++ one of course is intended to be correct, and the documentation agrees with it. I've updated the C header.
