### ISSUE TITLE
LADSPA clicks/pops

### ISSUE THREAD

**Issue by davidhealey** [breakfastquay/rubberband#20]
When using the LADSPA plugin in Audacity or Ardour (the hosts I've tried) Rubberband introduces pops and clicks at the start of the audio. This doesn't happen when using the CLI program with the same settings.

**Comment by davidhealey** [comment]
I think I might have solved the issue. I edited the ladspa code to increase the buffer and reserve values from 1024 to 2048 and so far it seems the clicks/pops issue is gone.

**Comment by davidhealey** [comment]
Btw I made a fork including this modification and I also merged FalkTX's LV2 addition.

https://github.com/davidhealey/rubberband

**Comment by davidhealey** [comment]
Well my fix was not a fix, I'm still experiencing issues when using rubberband as a plugin. I'm noticing it mainly with the cents parameter.

Example is attached
[rubberband artefacts.zip](https://github.com/breakfastquay/rubberband/files/4653051/rubberband.artefacts.zip)

**Comment by cannam** [comment]
Please give v2.0 (or the current repo default branch) a try if you haven't already - there were significant changes to the handling of real-time pitch changes in this release and a corresponding overhaul of the LADSPA plugin. (There's also now an LV2 plugin in the repo, though this wasn't in 2.0.)

**Comment by davidhealey** [comment]
> Please give v2.0 (or the current repo default branch) a try if you haven't already - there were significant changes to the handling of real-time pitch changes in this release and a corresponding overhaul of the LADSPA plugin. (There's also now an LV2 plugin in the repo, though this wasn't in 2.0.)

Thanks, I'll give it a try!

**Comment by davidhealey** [comment]
Yes that seems much better, I didn't notice any pops/clicks :)
