### ISSUE TITLE
C#/VB .NET port available?

### ISSUE THREAD

**Issue by Freefall63** [breakfastquay/rubberband#3]
Hello, I´d love to use the rubberband phase vocoder pitch shifter in my application. Unfortunately, it must not have any external dependencies and therefore target .NET.

Is there any port for .NET available or planned? Would be really cool.

At the moment I use the Bernsee phase vocoder instead: [https://github.com/naudio/NAudio/blob/master/NAudio/Wave/SampleProviders/SMBPitchShiftingSampleProvider.cs](https://github.com/naudio/NAudio/blob/master/NAudio/Wave/SampleProviders/SMBPitchShiftingSampleProvider.cs).

I´d really like to explore your approach and compare.

Thanks for reply.

**Comment by cannam** [comment]
There is such a thing now, in the repo (directories called `rubberband-sharp` and `rubberband-dll`, about to move to a subdir called `dotnet` in the forthcoming release)
