### ISSUE TITLE
Broken cross-compilation with meson

### ISSUE THREAD

**Issue by BtbN** [breakfastquay/rubberband#38]
Since 1.9.1 removed the autotools based build system, I was forced to use meson.
However, cross-compiling using meson has so far proven impossible.

The reason is a pretty simple one:
https://github.com/breakfastquay/rubberband/blob/default/meson.build#L20

Here the `system` variable is taken from build_machine instead of host_machine, thus on a build for Windows from Linux, it won't be "windows", and the build script will enable a bunch of non-Windows things, breaking the build.

Just replacing that with `host_machine.system()` appears to fix the build.

**Comment by cannam** [comment]
Thank you for the report! I've made that change.
