### ISSUE TITLE
hiss / white noise after rubberband processing

### ISSUE THREAD

**Issue by m4yer** [breakfastquay/rubberband#57]
Hi there! I've encountered a problem that after processing .wav file I get .wav file with hiss / white noise effect.

I tried to apply ratio of 1.0 - meaning that resulting file is the same length as the original but can please someone shed a light on what did I do wrong that I get these issues?

**Comment by m4yer** [comment]
@cannam

**Comment by cannam** [comment]
Hi there - processing the file how? Are you using the `rubberband` command-line tool, or is this your own code using the `RubberBandStretcher` class from C++?

**Comment by m4yer** [comment]
@cannam, I'm executing it from Java

**Comment by m4yer** [comment]
@cannam, not sure if I'm allowed to put the links here, but I'll try:
Before it my file sounds like this: https://drive.google.com/file/d/1OcPUJNTVyYo8589otdrNyPS9QH4EPXOw/view?usp=sharing
After processing: https://drive.google.com/file/d/1bT_e1U0QEsBCm0Q2RWrSSc3a5kiaVAKE/view?usp=sharing

**Comment by cannam** [comment]
I checked your files - I've never seen a result like that and I can't think of any obvious reason why it would happen. The noise level looks like what you would get if you quantized the output harshly, maybe to 8 bits. You don't have some strange processing pipeline going on on the Java side, with a very limited audio codec in the middle or something?

**Comment by m4yer** [comment]
@cannam, most probably I'm doing something wrong, because if I do the same with cmd-line version it works fine.
