### ISSUE TITLE
How to jump to position in a song?

### ISSUE THREAD

**Issue by AmyXS** [breakfastquay/rubberband#6]
Hi,

I couldn't find a method that allows for setting the playhead position, wonder if this is supported? I noticed the demo app has a slider that allows for jumping to a different position, could you please explain how this is done?

Cheers!

**Comment by jamiebullock** [comment]
Hi @swan488, I don't think jumping position is really the job of RubberBand.

You pass in blocks of samples to `RubberBandStretcher::process()` and retrieve them (stretched) from `RubberBandStretcher::retrieve()`. So if your input block "jumps" with respect to some larger buffer of audio, then the output from RubberBand will reflect that.

**Comment by swan488** [comment]
That makes sense, thanks for answering!
