### ISSUE TITLE
v3.1.1 Android makefile needs updating

### ISSUE THREAD

**Issue by jimsimonz** [breakfastquay/rubberband#75]
A couple of files have changed so the Android.mk file needs changing:

`RUBBERBAND_SRC_FILES := \
	$(RUBBERBAND_SRC_PATH)/rubberband-c.cpp \
	$(RUBBERBAND_SRC_PATH)/RubberBandStretcher.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/AudioCurveCalculator.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/CompoundAudioCurve.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/HighFrequencyAudioCurve.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/SilentAudioCurve.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/PercussiveAudioCurve.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/StretcherChannelData.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/R2Stretcher.cpp \
	$(RUBBERBAND_SRC_PATH)/faster/StretcherProcess.cpp \
	$(RUBBERBAND_SRC_PATH)/common/BQResampler.cpp \
	$(RUBBERBAND_SRC_PATH)/common/Profiler.cpp \
	$(RUBBERBAND_SRC_PATH)/common/Resampler.cpp \
	$(RUBBERBAND_SRC_PATH)/common/FFT.cpp \
	$(RUBBERBAND_SRC_PATH)/common/Allocators.cpp \
	$(RUBBERBAND_SRC_PATH)/common/StretchCalculator.cpp \
	$(RUBBERBAND_SRC_PATH)/common/sysutils.cpp \
	$(RUBBERBAND_SRC_PATH)/common/mathmisc.cpp \
	$(RUBBERBAND_SRC_PATH)/common/Thread.cpp \
	$(RUBBERBAND_SRC_PATH)/common/Log.cpp \
	$(RUBBERBAND_SRC_PATH)/finer/R3Stretcher.cpp 
`

the above list builds, added log.cpp, R3Stretcher and StretcherImpl changed names.

I also changed TARGET_ARCH_ABI	:= arm64-v8a for 64 bit and removed the throw from BQResampler as this wasn't compiling. 

With the simple sample's Application.mk the following also needed changing as the STL lib's no longer valid:

APP_STL := c++_static
APP_ABI := arm64-v8a

**Comment by cannam** [comment]
Thank you! I have pushed these fixes. I confess that (as you can probably tell) it's been a while since I had a working Android development environment - I wonder how practical it is to set one up in CI.

**Comment by jimsimonz** [comment]
Nice it works
