### ISSUE TITLE
Fade in on starting processing with finer (R3 engine)

### ISSUE THREAD

**Issue by jimsimonz** [breakfastquay/rubberband#85]
Hi,

I'm testing with the latest R3 algorithm and it seems to add a fade in at the start of processing. 

Options = OptionProcessRealTime | OptionEngineFiner causes this, if I leave the finer flag off, the fade in doesn't occur.

Any ideas? tried with different window settings and it's the same.

**Comment by cannam** [comment]
Can you check that you are following the recommendations at [Output in real-time mode is not aligned with the timing I expected](https://breakfastquay.com/rubberband/integration.html#faqs) ?

**Comment by jimsimonz** [comment]
thanks I wasn't aware and hadn't spotted this in the docs.
