### ISSUE TITLE
Undefined Symbols Error

### ISSUE THREAD

**Issue by mattingale** [breakfastquay/rubberband#9]
Hello there, I've followed the proper install instructions on a 10.12.6 Mac and included the "rubberband/RubberBandStretcher.h" and copied over the required src folder and rubberband folder but I'm getting errors at compile time that the rubberband functions are not defined...
here's an example..

    "RubberBand::RubberBandStretcher::~RubberBandStretcher()", referenced from:
            autoTune::autoTune() in MainApp.o
ld: symbol(s) not found for architecture x86_64

hope to hear back soon, I'm loving the way this is coded and can't wait to hear it in action

I've also tried the portaudio approach by dropping in the compiled .dylib and .a and .h for rubberband and that didn't get as far as these errors

**Comment by romancfischer** [comment]
+1
when I compile for iOS ( with Makefile.ios ) I get the following errors:

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: lib/librubberband.dev.a(Profiler.dev.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: lib/librubberband.dev.a(Allocators.dev.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: armv7 file: lib/librubberband.dev.a(Thread.dev.o) has no symbols

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: i386 file: lib/librubberband.sim.a(Profiler.sim.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: i386 file: lib/librubberband.sim.a(Allocators.sim.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: i386 file: lib/librubberband.sim.a(Thread.sim.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: lib/librubberband.sim.a(Profiler.sim.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: lib/librubberband.sim.a(Allocators.sim.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: for architecture: x86_64 file: lib/librubberband.sim.a(Thread.sim.o) has no symbols

how can I make it work? Any help highly appreciated!

**Comment by cannam** [comment]
Closing as probably obsoleted by either the newer build system, the single-file compilation support, or both. Please open new issues if problems still persist at this later date.
